/** @format */

export const cards = {
  "79c73eea-9a43-4017-9117-79ae0df1de73": {
    id: "79c73eea-9a43-4017-9117-79ae0df1de73",
    type: "note",
    position: {
      top: 0,
      left: 0,
    },
    size: {
      width: 300,
      height: 200,
    },
    shortcut: "",
    title: "",
    data: "some text Lorem some textsome textsome textsome textsome textsome textsome textsome text",
    folded: false,
    tags: [],
  },
  "030d173b-d2bf-47e9-8c08-e252b58ead92": {
    id: "030d173b-d2bf-47e9-8c08-e252b58ead92",
    type: "note",
    position: {
      top: 210,
      left: 0,
    },
    size: {
      width: 300,
      height: 200,
    },
    shortcut: "",
    title: "",
    data: "some text Lorem some textsome textsome textsome textsome textsome textsome textsome text",
    folded: false,
    tags: [],
  },
  "3aa7cadb-7f4a-49fa-a6bb-1133b274235d": {
    id: "3aa7cadb-7f4a-49fa-a6bb-1133b274235d",
    type: "note",
    position: {
      top: 420,
      left: 0,
    },
    size: {
      width: 300,
      height: 200,
    },
    shortcut: "",
    title: "",
    data: "some text Lorem some textsome textsome textsome textsome textsome textsome textsome text",
    folded: false,
    tags: [],
  },
  "ee3bb30a-c0d3-4f5a-a67b-12ef913d24f8": {
    id: "ee3bb30a-c0d3-4f5a-a67b-12ef913d24f8",
    type: "note",
    position: {
      top: 630,
      left: 0,
    },
    size: {
      width: 300,
      height: 200,
    },
    shortcut: "",
    title: "",
    data: "some text Lorem some textsome textsome textsome textsome textsome textsome textsome text",
    folded: false,
    tags: [],
  },
  "cb4c0292-46f1-45f9-916b-9eef62994493": {
    id: "cb4c0292-46f1-45f9-916b-9eef62994493",
    type: "markdown",
    position: {
      top: 0,
      left: 0,
    },
    size: {
      width: 450,
      height: 300,
    },
    shortcut: "",
    title: "",
    data: "### Mushololo",
    folded: false,
    tags: [],
  },
}

export const BOARDS = {
  b001: {
    cards: {
      "1cb0b77d-8c63-47c0-a344-520ae54a1048": {
        id: "1cb0b77d-8c63-47c0-a344-520ae54a1048",
        type: "note",
        position: {top: 0, left: 0},
        size: {width: 300, height: 200},
        shortcut: "",
        title: "Subsequent Navigations",
        data: "On subsequent navigations, Client Components are rendered entirely on the client, without the server-rendered HTML.\n\nThis means the Client Component JavaScript bundle is downloaded and parsed. Once the bundle is ready, React will use the RSC Payload to reconcile the Client and Server Component trees, and update the DOM.",
        folded: false,
        tags: [],
      },
      "9207040b-5728-4cc0-9b9d-af302d72f616": {
        id: "9207040b-5728-4cc0-9b9d-af302d72f616",
        type: "note",
        position: {top: 210, left: 0},
        size: {width: 300, height: 200},
        shortcut: "",
        title: "useUser() and useSession()",
        data: "Previously, useUser and useSession could only be called from inside the <SignedIn> component. This restriction has been relaxed, but now developers must manually handle the possibility the user and session objects may not be loaded when the hook is called.\n\nIn a future version, we plan to support React <Suspense /> to make this even easier.",
        folded: false,
        tags: [],
      },
      "e4cba601-58ed-46ff-a454-5ff6b0c00fa5": {
        id: "e4cba601-58ed-46ff-a454-5ff6b0c00fa5",
        type: "code",
        position: {top: 0, left: 310},
        size: {width: 300, height: 200},
        shortcut: "",
        title: "add",
        data: {
          lang: "javascript",
          code: "function add(a, b) {\n  return a + b;\n}",
        },
        folded: false,
        tags: [],
      },
      "943b31dc-cd54-49a4-922d-f0071fbb7155": {
        id: "943b31dc-cd54-49a4-922d-f0071fbb7155",
        type: "code",
        position: {top: 210, left: 310},
        size: {width: 300, height: 200},
        shortcut: "",
        title: "calldb",
        data: {
          lang: "javascript",
          code: 'export async function queryItems() {\n  try {\n    const command = new QueryCommand({\n      TableName: "movies",\n      ExpressionAttributeValues: {\n        ":condition": {\n          S: "boarda",\n        },\n      },\n      KeyConditionExpression: "board = :condition",\n    })\n    const reponse = await dbclient.send(command)\n    console.log(reponse)\n  } catch (err) {\n    console.log(err)\n  }\n}',
        },
        folded: false,
        tags: [],
      },
      "52fed877-7482-4bd4-92ef-7e2757d5d422": {
        id: "52fed877-7482-4bd4-92ef-7e2757d5d422",
        type: "markdown",
        position: {top: 5.000457763671875, left: 620.800048828125},
        size: {width: 250, height: 350},
        shortcut: "",
        title: "",
        data: "### Carthage\n\nCarthage[a] was an ancient city on the eastern side of the Lake of Tunis in what is now Tunisia. Carthage was one of the most important trading hubs of the Ancient Mediterranean and one of the most affluent cities of the classical world. It became the capital city of the civilisation of Ancient Carthage and later Roman Carthage.\n\nThe city developed from a Phoenician colony into the capital of a Punic empire which dominated large parts of the Southwest Mediterranean during the first millennium BC.[1] The legendary Queen Elissa, Alyssa or Dido, originally from Tyre, is regarded as the founder of the city,[2] though her historicity has been questioned. In the myth, Dido asked for land from a local tribe, which told her that she could get as much land as an oxhide could cover. She cut the oxhide into strips and laid out the perimeters of the new city.[3] As Carthage prospered at home, the polity sent colonists abroad as well as magistrates to rule the colonies.[4]\n\nThe ancient city was destroyed in the nearly-three year siege of Carthage by the Roman Republic during the Third Punic War in 146 BC. It was re-developed a century later as Roman Carthage, which became the major city of the Roman Empire in the province of Africa. The question of Carthaginian decline and demise has remained a subject of literary, political, artistic, and philosophical debates in both ancient and modern histories.[4][5]",
        folded: false,
        tags: [],
      },
    },
  },
  b002: {
    cards: {
      "432bafd4-b898-454f-bd0b-2c73b3277751": {
        id: "432bafd4-b898-454f-bd0b-2c73b3277751",
        type: "markdown",
        position: {
          top: 0,
          left: 310,
        },
        size: {
          width: 250,
          height: 300,
        },
        shortcut: "",
        title: "",
        data: "### Hi ! Double tap to edit",
        folded: false,
        tags: [],
      },
      "2dc5d891-0804-4880-9641-6ae24bfe0cfb": {
        id: "2dc5d891-0804-4880-9641-6ae24bfe0cfb",
        type: "code",
        position: {
          top: 0,
          left: 0,
        },
        size: {
          width: 300,
          height: 200,
        },
        shortcut: "",
        title: "foo",
        data: {
          lang: "javascript",
          code: 'const foo = () => {\n  console.log("refacroting ...")\n}',
        },
        folded: false,
        tags: [],
      },
    },
  },
  b003: {
    cards: {
      "432bafd4-b898-454f-bd0b-2c73b3277751": {
        id: "432bafd4-b898-454f-bd0b-2c73b3277751",
        type: "markdown",
        position: {
          top: 0,
          left: 310,
        },
        size: {
          width: 250,
          height: 300,
        },
        shortcut: "",
        title: "",
        data: "### Hi ! Double tap to edit",
        folded: false,
        tags: [],
      },
      "2dc5d891-0804-4880-9641-6ae24bfe0cfb": {
        id: "2dc5d891-0804-4880-9641-6ae24bfe0cfb",
        type: "code",
        position: {
          top: 0,
          left: 0,
        },
        size: {
          width: 300,
          height: 200,
        },
        shortcut: "",
        title: "foo",
        data: {
          lang: "javascript",
          code: 'const foo = () => {\n  console.log("refacroting ...")\n}',
        },
        folded: false,
        tags: [],
      },
      "1cb0b77d-8c63-47c0-a344-520ae54a1048": {
        id: "1cb0b77d-8c63-47c0-a344-520ae54a1048",
        type: "note",
        position: {top: 0, left: 0},
        size: {width: 300, height: 200},
        shortcut: "",
        title: "Subsequent Navigations",
        data: "On subsequent navigations, Client Components are rendered entirely on the client, without the server-rendered HTML.\n\nThis means the Client Component JavaScript bundle is downloaded and parsed. Once the bundle is ready, React will use the RSC Payload to reconcile the Client and Server Component trees, and update the DOM.",
        folded: false,
        tags: [],
      },
      "9207040b-5728-4cc0-9b9d-af302d72f616": {
        id: "9207040b-5728-4cc0-9b9d-af302d72f616",
        type: "note",
        position: {top: 210, left: 0},
        size: {width: 300, height: 200},
        shortcut: "",
        title: "useUser() and useSession()",
        data: "Previously, useUser and useSession could only be called from inside the <SignedIn> component. This restriction has been relaxed, but now developers must manually handle the possibility the user and session objects may not be loaded when the hook is called.\n\nIn a future version, we plan to support React <Suspense /> to make this even easier.",
        folded: false,
        tags: [],
      },
      "e4cba601-58ed-46ff-a454-5ff6b0c00fa5": {
        id: "e4cba601-58ed-46ff-a454-5ff6b0c00fa5",
        type: "code",
        position: {top: 0, left: 310},
        size: {width: 300, height: 200},
        shortcut: "",
        title: "add",
        data: {
          lang: "javascript",
          code: "function add(a, b) {\n  return a + b;\n}",
        },
        folded: false,
        tags: [],
      },
      "943b31dc-cd54-49a4-922d-f0071fbb7155": {
        id: "943b31dc-cd54-49a4-922d-f0071fbb7155",
        type: "code",
        position: {top: 210, left: 310},
        size: {width: 300, height: 200},
        shortcut: "",
        title: "calldb",
        data: {
          lang: "javascript",
          code: 'export async function queryItems() {\n  try {\n    const command = new QueryCommand({\n      TableName: "movies",\n      ExpressionAttributeValues: {\n        ":condition": {\n          S: "boarda",\n        },\n      },\n      KeyConditionExpression: "board = :condition",\n    })\n    const reponse = await dbclient.send(command)\n    console.log(reponse)\n  } catch (err) {\n    console.log(err)\n  }\n}',
        },
        folded: false,
        tags: [],
      },
      "52fed877-7482-4bd4-92ef-7e2757d5d422": {
        id: "52fed877-7482-4bd4-92ef-7e2757d5d422",
        type: "markdown",
        position: {top: 5.000457763671875, left: 620.800048828125},
        size: {width: 250, height: 350},
        shortcut: "",
        title: "",
        data: "### Carthage\n\nCarthage[a] was an ancient city on the eastern side of the Lake of Tunis in what is now Tunisia. Carthage was one of the most important trading hubs of the Ancient Mediterranean and one of the most affluent cities of the classical world. It became the capital city of the civilisation of Ancient Carthage and later Roman Carthage.\n\nThe city developed from a Phoenician colony into the capital of a Punic empire which dominated large parts of the Southwest Mediterranean during the first millennium BC.[1] The legendary Queen Elissa, Alyssa or Dido, originally from Tyre, is regarded as the founder of the city,[2] though her historicity has been questioned. In the myth, Dido asked for land from a local tribe, which told her that she could get as much land as an oxhide could cover. She cut the oxhide into strips and laid out the perimeters of the new city.[3] As Carthage prospered at home, the polity sent colonists abroad as well as magistrates to rule the colonies.[4]\n\nThe ancient city was destroyed in the nearly-three year siege of Carthage by the Roman Republic during the Third Punic War in 146 BC. It was re-developed a century later as Roman Carthage, which became the major city of the Roman Empire in the province of Africa. The question of Carthaginian decline and demise has remained a subject of literary, political, artistic, and philosophical debates in both ancient and modern histories.[4][5]",
        folded: false,
        tags: [],
      },
    },
  },
}
